### PR TITLE
FSE petition single fixes

### PR DESCRIPTION
**Pull request by jaymcp**
Ref: https://github.com/amnestywebsite/humanity-theme/issues/246

**Steps to test**:
1. visit the site editor
2. edit the petition single template
3. blocks should not throw invalidation errors

### CODE REVIEW

**Review by Gentyspun — DISMISSED** [review]
LGTM 👍

**Review by Gentyspun — APPROVED** [review]
Still good 👍

**Comment by jaymcp** [comment]
I don't know what GitHub's doing here, but those dismissals are automated. Sorry for the trouble.

**Comment by jaymcp** [comment]
For now, ignore any of these messages - no need to re-approve:

**Pull request merged**
