### PR TITLE
Index Template: Remove PHP version and update HTML version

### PR DESCRIPTION
**Pull request by mikachan**
Ref: https://github.com/amnestywebsite/humanity-theme/issues/346. Part of https://github.com/amnestywebsite/humanity-theme/issues/246

This removes the index.php template and updates the index.html template to include a `main` container. This should also fix an issue with a blank Editor loading on the initial `/wp-admin/site-editor.php` page.

**Steps to test**:
1. Ensure the correct content is loaded on the front end of your test site on various pages and posts.
2. In wp-admin, go to Appearance -> Editor and ensure that the index template is rendered successfully, rather than a blank Editor.

| site-editor.php Before | site-editor.php After |
| ---- | ---- |
|  |  |

**Considerations**:
- Accessibility
  - Regions (semantic HTML tags, e.g. `<section>`; [landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles); etc.)
  - Screen reader compatibility, labels ([`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby), etc.)
  - Keyboard navigability
- Localisation
- RTL

### CODE REVIEW

**Review by jffng — COMMENTED** [review]
Strange, the editor is not loading the index template by default, but both 404 and index templates show up in the Templates section: 

Design | Templates
--- | ---
Screenshot 2024-08-05 at 12 15 28 PM | Screenshot 2024-08-05 at 12 15 30 PM

Trying to figure out what's going on.

**Comment by mikachan** [comment]
> Strange, the editor is not loading the index template by default, but both 404 and index templates show up in the Templates section:

This is similar to what I was seeing before I made this PR. I've also changed my reading settings to a static homepage and posts page, and if I change back to "Your latest posts", then the Editor no longer loads a template (like your screenshot). Maybe this is something to be fixed upstream, it sounds like we need a better fallback when the Editor is confused about what template to use.

**Comment by matiasbenedetto** [comment]
This change doesn't seem to be changing the editor page for me. I'm still getting this screen:

image

**Comment by matiasbenedetto** [comment]
An alternative fix that is making the site editor load in my local env: https://github.com/amnestywebsite/humanity-theme/pull/341

**Comment by jffng** [comment]
>  I've also changed my reading settings to a static homepage and posts page

Ah yes, now it loads when I change the reading settings to display a static page as the home page. 

> it sounds like we need a better fallback when the Editor is confused about what template to use.

Yeah, the black editor looks like a bug when it can't find a template to render.

**Comment by mikachan** [comment]
I've opened an issue upstream for the blank Editor issue: https://github.com/WordPress/gutenberg/issues/64303

**Review by jaymcp — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
